kind: Template
apiVersion: v1
metadata:
  name: appdev-documentation-configmap
  annotations:
    openshift.io/display-name: "Appdev Documentation - Configuration"
    description: This application contains the Appdev Documentation configuration settings
    tags: instant-app,documentation,launchpad
    iconClass: icon-shadowman
    template.openshift.io/long-description: This application contains the Appdev Documentation configuration settings
    template.openshift.io/provider-display-name: Red Hat, Inc.
    template.openshift.io/documentation-url: https://github.com/openshiftio/launchpad-templates
    template.openshift.io/support-url: https://access.redhat.com
message: "The following service has been created in your project: launchpad-configuration.\n\nFor more information about using this template, including OpenShift considerations, see https://github.com/openshiftio"
labels:
  template: appdev-documentation-configmap
parameters:
- name: LAUNCHPAD_TRACKER_SEGMENT_TOKEN
  displayName: Segment Token
  description: The token to use for Segment tracking. Leaving this empty will disable
    tracking. This must be set to the proper tokens for staging and production!
objects:
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: appdev-documentation
  data:
    tracker.segment.token: ${LAUNCHPAD_TRACKER_SEGMENT_TOKEN}
